package io.github.cyfko.inputspec.processor.spi;

import io.github.cyfko.inputspec.spi.FormContext;

import java.util.*;

/**
 * Default implementation of {@link FormContext}, constructed by the
 * InputSpec annotation processor after all fields of a @FormSpec type
 * have been processed.
 *
 * <p>Immutable once built. The processor builds it with the
 * {@link Builder} and passes it to each registered {@link io.github.cyfko.inputspec.spi.FormContributor}.
 */
public final class DefaultFormContext implements FormContext {

    private final String       formId;
    private final String       submitUri;
    private final String       submitMethod;
    private final List<String> locales;
    private final List<String> transformedFieldRefs;
    private final List<String> allFieldNames;
    private final Map<String, String> transformedFieldJsonMap;
    private final int          defaultPageSize;
    private final int          maxPageSize;

    private DefaultFormContext(Builder b) {
        this.formId                 = b.formId;
        this.submitUri              = b.submitUri;
        this.submitMethod           = b.submitMethod;
        this.locales                = Collections.unmodifiableList(new ArrayList<>(b.locales));
        this.transformedFieldRefs   = Collections.unmodifiableList(new ArrayList<>(b.transformedFieldRefs));
        this.allFieldNames          = Collections.unmodifiableList(new ArrayList<>(b.allFieldNames));
        this.transformedFieldJsonMap = Collections.unmodifiableMap(new LinkedHashMap<>(b.transformedFieldJsonMap));
        this.defaultPageSize        = b.defaultPageSize;
        this.maxPageSize            = b.maxPageSize;
    }

    @Override public String       formId()       { return formId; }
    @Override public String       submitUri()     { return submitUri; }
    @Override public String       submitMethod()  { return submitMethod; }
    @Override public List<String> locales()       { return locales; }
    @Override public int          defaultPageSize() { return defaultPageSize; }
    @Override public int          maxPageSize()   { return maxPageSize; }

    @Override
    public List<String> transformedFieldRefs() { return transformedFieldRefs; }

    @Override
    public List<String> allFieldNames() { return allFieldNames; }

    @Override
    public Optional<String> transformedFieldJson(String ref) {
        return Optional.ofNullable(transformedFieldJsonMap.get(ref));
    }

    // ─── Builder ──────────────────────────────────────────────────────────────

    public static Builder builder(String formId) { return new Builder(formId); }

    public static final class Builder {
        private final String       formId;
        private String             submitUri              = "";
        private String             submitMethod           = "POST";
        private List<String>       locales                = new ArrayList<>();
        private final List<String> transformedFieldRefs   = new ArrayList<>();
        private final List<String> allFieldNames          = new ArrayList<>();
        private final Map<String, String> transformedFieldJsonMap = new LinkedHashMap<>();
        private int                defaultPageSize        = 20;
        private int                maxPageSize            = 100;

        private Builder(String formId) { this.formId = formId; }

        public Builder submitUri(String v)     { this.submitUri = v;     return this; }
        public Builder submitMethod(String v)  { this.submitMethod = v;  return this; }
        public Builder locales(List<String> v) { this.locales = v;       return this; }
        public Builder defaultPageSize(int v)  { this.defaultPageSize = v; return this; }
        public Builder maxPageSize(int v)      { this.maxPageSize = v;   return this; }

        /**
         * Records a field that was claimed and transformed by a FieldTransformer.
         *
         * @param ref      the ref name (e.g. "AGE") from FieldTransformer.fieldRefName()
         * @param fieldJson the generated JSON string for this field
         * @param logicalName the camelCase field name (e.g. "age") for projection list
         */
        public Builder addTransformedField(String ref, String fieldJson, String logicalName) {
            transformedFieldRefs.add(ref);
            transformedFieldJsonMap.put(ref, fieldJson);
            allFieldNames.add(logicalName);
            return this;
        }

        /**
         * Records a field generated by the default InputSpec pipeline.
         *
         * @param logicalName the camelCase field name (e.g. "email")
         */
        public Builder addDefaultField(String logicalName) {
            allFieldNames.add(logicalName);
            return this;
        }

        public DefaultFormContext build() {
            Objects.requireNonNull(formId, "formId must not be null");
            return new DefaultFormContext(this);
        }
    }
}
